pipelineJob('job-dsl-plugin') {
  definition {
    cpsScm {
      scm {
        git {
          remote {
            url('https://github.com/todvildes/dsl-jobs.git')
          }
          branch('*/main')
        }
      }
      lightweight()
    }
  }
}